### ISSUE TITLE
[Feature Request]: BitBucket and Gitlab Authentication

### ISSUE THREAD

**Issue by Adi-11** [open-certs/oc-frontend#2] opened 2022-02-16 17:59 UTC
### Preflight Checklist

- [X] I have read the Contribution.md for this project.
- [X] I agree to follow the Code of Conduct that this project adheres to.
- [X] I have searched the feature for a feature request that matches the one I want to file, without success.

### Problem Description

Bitbucket and Gitlab Authentication don't exist but much open-source software is still maintained on Both, So both of them must be integrated.

### Proposed Solution

Based on the Github authentication (Already implemented), there is only a need for an API call specific to Bitbucket or Gitlab.
And Accordingly maintaining and storing data in the front end.

### Alternatives Considered

NA

**Comment by MadhusreeBera** [comment] 2022-02-28 18:40
Hello, I want to contribute in this project. Can you please assign this issue to me

**Comment by MitAbhay** [comment] 2022-03-13 10:04
@Adi-11  If the issue is still pending, can I go through it?

**Closed as completed** 2022-03-14 16:43 UTC
Labels: enhancement, GSSoC22, Level2, assigned
